using System.Net;
using Microsoft.AspNetCore.Mvc.Testing;
using Xunit;
using Chirp.Web;
using Chirp.Core.Domain;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Identity;

namespace MyChat.Razor.Tests;

public class ApiTests : IClassFixture<CustomWebApplicationFactory>

{
    //Tests for website using temporary version
    private readonly CustomWebApplicationFactory _factory;
    private readonly HttpClient _client;

    public ApiTests(CustomWebApplicationFactory factory)
    {
        _factory = factory;
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task PublicTimeline_ReturnsSuccessStatusCode()
    {
        //Act
        var response = await _client.GetAsync("/");

        //Assert
        response.EnsureSuccessStatusCode();
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    } //git2

    [Fact]
    public async Task PublicTimeline_ContainsHelgeCheep()
    {
        //Act
        var response = await _client.GetAsync("/user/Roger%20Histand");
        var content = await response.Content.ReadAsStringAsync();

        //Assert
        Assert.Contains("understand", content);
    }

    [Fact]
    public async Task UserTimeline_Adrian_ReturnsSuccessStatusCode()
    {
        //Act
        var response = await _client.GetAsync("/user/Adrian");

        //Assert
        response.EnsureSuccessStatusCode();
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task UserTimeline_Adrian_ContainsAdrianCheep()
    {
        //Act
        var response = await _client.GetAsync("/user/Adrian");
        var content = await response.Content.ReadAsStringAsync();

        //Assert
        Assert.Contains("Adrian", content);
        Assert.Contains("Hej, velkommen til kurset.", content);
    }

    [Fact]
    public async Task PublicTimeline_ContainsPublicTimelineHeader()
    {
        //Act
        var response = await _client.GetAsync("/");
        var content = await response.Content.ReadAsStringAsync();

        //Assert
        Assert.Contains("Public Timeline", content);
    }

    [Fact]
    public async Task UserTimeline_ContainsUsernameInHeader()
    {
        //Act
        var response = await _client.GetAsync("/user/Adrian");
        var content = await response.Content.ReadAsStringAsync();

        //Assert
        Assert.Contains("Hej, velkommen til kurset.", content);
    }

    [Fact]
    public async Task AuthenticatedUser_CanPostCheep_AndSeeItOnTimeline()
    {
        // Arrange
        var username = "TestUser";

        // Create the user in the in-memory database
        using var scope = _factory.Services.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<Author>>();
        var user = await userManager.FindByNameAsync(username);
        if (user == null)
        {
            // Ensure the test user's Id matches the id generated by TestAuthHandler
            var generatedId = Math.Abs(username.GetHashCode() % 1000000);
            user = new Author { Id = generatedId, UserName = username, Email = $"{username}@example.com" };
            var result = await userManager.CreateAsync(user);
            if (!result.Succeeded)
                throw new Exception("Failed to create test user");
        }

        // Use an authenticated test client that populates ClaimsPrincipal correctly
        var client = _factory.CreateAuthenticatedClient(username);

        var newCheepText = "Hello world!";
        var formData = new FormUrlEncodedContent(new[]
        {
        new KeyValuePair<string, string>("NewCheepText", newCheepText)
    });

        // Act: Post a new cheep
        var postResponse = await client.PostAsync($"/private/{username}", formData);

        // Ensure POST succeeded (redirect status)
        Assert.True(postResponse.StatusCode == HttpStatusCode.Redirect
                    || postResponse.StatusCode == HttpStatusCode.Found,
                    $"Unexpected status code: {postResponse.StatusCode}");

        // Follow redirect to get the updated timeline
        var redirectedResponse = await client.GetAsync($"/private/{username}");
        redirectedResponse.EnsureSuccessStatusCode();
        var content = await redirectedResponse.Content.ReadAsStringAsync();

        // Assert: The new cheep appears on the timeline
        Assert.Contains(newCheepText, content);
        Assert.Contains(username, content);
    }
}