name: Release Chirp

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch: # Optional manual trigger

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/Chirp.CLI

      - name: Build
        run: |
          dotnet publish ./src/Chirp.CLI/Chirp.CLI.csproj \
            --configuration Release \
            --runtime ${{ matrix.os == 'windows-latest' && 'win-${{ matrix.arch }}' || matrix.os == 'macos-latest' && 'osx-${{ matrix.arch }}' || 'linux-${{ matrix.arch }}' }} \
            --self-contained true \
            -o ./artifacts/${{ matrix.os }}-${{ matrix.arch }}

      - name: Package as Zip
        run: |
          cd artifacts
          zip -r Chirp-${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chirp-${{ matrix.os }}-${{ matrix.arch }}
          path: ./artifacts/Chirp-${{ matrix.os }}-${{ matrix.arch }}.zip
