name: Release Chirp

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0
  workflow_dispatch: # Optional manual trigger

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            arch: x64
          - os: ubuntu-latest
            runtime: linux-arm64
            arch: arm64
          - os: windows-latest
            runtime: win-x64
            arch: x64
          - os: windows-latest
            runtime: win-arm64
            arch: arm64
          - os: macos-latest
            runtime: osx-x64
            arch: x64
          - os: macos-latest
            runtime: osx-arm64
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./src/Chirp.CLI
      
      - name: Build & Publish
        run: dotnet publish ./src/Chirp.CLI/Chirp.CLI.csproj --configuration Release --runtime ${{ matrix.runtime }} --self-contained false -o ./artifacts/${{ matrix.runtime }}
      
      - name: Package as Zip (Unix)
        if: runner.os != 'Windows'
        run: |
          cd artifacts
          zip -r ${{ matrix.runtime }}.zip ${{ matrix.runtime }}
      
      - name: Package as Zip (Windows)
        if: runner.os == 'Windows'
        run: |
          cd artifacts
          Compress-Archive -Path ${{ matrix.runtime }} -DestinationPath ${{ matrix.runtime }}.zip
        shell: pwsh
      
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chirp-${{ matrix.runtime }}
          path: ./artifacts/${{ matrix.runtime }}.zip
